"use client";

export interface PaletteColors {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  border: string;
  muted: string;
  mutedForeground: string;
  ring: string;
  gradientFrom: string;
  gradientTo: string;
}

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  swatch: string;
  light: PaletteColors;
  dark: PaletteColors;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "royal",
    name: "Royal Purple",
    description: "Luxury",
    swatch: "#6D4FD6",
    light: {
      background: "#FAFAFB",
      foreground: "#1E1B2E",
      card: "#FFFFFF",
      cardForeground: "#1E1B2E",
      primary: "#3730A3",
      primaryForeground: "#FFFFFF",
      secondary: "#4C1D95",
      secondaryForeground: "#FFFFFF",
      accent: "#E8C468",
      accentForeground: "#2A1F03",
      border: "#E4E1F0",
      muted: "var(--color-muted)",
      mutedForeground: "#6B6580",
      ring: "#6D4FD6",
      gradientFrom: "#3730A3",
      gradientTo: "#E8C468",
    },
    dark: {
      background: "#0B0A14",
      foreground: "#F4F2FA",
      card: "#161325",
      cardForeground: "#F4F2FA",
      primary: "#6D4FD6",
      primaryForeground: "#FFFFFF",
      secondary: "#9B7BE8",
      secondaryForeground: "#15122A",
      accent: "#F0CE7A",
      accentForeground: "#2A1F03",
      border: "#2A2640",
      muted: "#1F1B33",
      mutedForeground: "#A39DBD",
      ring: "#9B7BE8",
      gradientFrom: "#6D4FD6",
      gradientTo: "#F0CE7A",
    },
  },
  {
    id: "emerald",
    name: "Emerald",
    description: "Nature",
    swatch: "#10B981",
    light: {
      background: "#F7FBF9",
      foreground: "#0E2A22",
      card: "#FFFFFF",
      cardForeground: "#0E2A22",
      primary: "#047857",
      primaryForeground: "#FFFFFF",
      secondary: "#0D9488",
      secondaryForeground: "#FFFFFF",
      accent: "#D4B36A",
      accentForeground: "#2A1F03",
      border: "#DCEAE3",
      muted: "#EAF5EF",
      mutedForeground: "#5E7A70",
      ring: "#10B981",
      gradientFrom: "#047857",
      gradientTo: "#D4B36A",
    },
    dark: {
      background: "#06120F",
      foreground: "#EAF6EF",
      card: "#0F231C",
      cardForeground: "#EAF6EF",
      primary: "#34D399",
      primaryForeground: "#06120F",
      secondary: "#2DD4BF",
      secondaryForeground: "#06120F",
      accent: "#E8C97A",
      accentForeground: "#2A1F03",
      border: "#1C3A30",
      muted: "#142A22",
      mutedForeground: "#8FB3A6",
      ring: "#34D399",
      gradientFrom: "#10B981",
      gradientTo: "#E8C97A",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Modern",
    swatch: "#0EA5E9",
    light: {
      background: "#F6FAFD",
      foreground: "#0E2233",
      card: "#FFFFFF",
      cardForeground: "#0E2233",
      primary: "#0369A1",
      primaryForeground: "#FFFFFF",
      secondary: "#0E7490",
      secondaryForeground: "#FFFFFF",
      accent: "#F59E0B",
      accentForeground: "#2A1700",
      border: "#DCEAF5",
      muted: "#EAF4FB",
      mutedForeground: "#5C7A8E",
      ring: "#0EA5E9",
      gradientFrom: "#0369A1",
      gradientTo: "#22D3EE",
    },
    dark: {
      background: "#06141F",
      foreground: "#E9F5FC",
      card: "#0E2433",
      cardForeground: "#E9F5FC",
      primary: "#38BDF8",
      primaryForeground: "#06141F",
      secondary: "#22D3EE",
      secondaryForeground: "#06141F",
      accent: "#FBBF24",
      accentForeground: "#2A1700",
      border: "#1C3A4D",
      muted: "#132B3B",
      mutedForeground: "#8AAFC2",
      ring: "#38BDF8",
      gradientFrom: "#0EA5E9",
      gradientTo: "#FBBF24",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm",
    swatch: "#F97316",
    light: {
      background: "#FFFAF5",
      foreground: "#2B1B12",
      card: "#FFFFFF",
      cardForeground: "#2B1B12",
      primary: "#C2410C",
      primaryForeground: "#FFFFFF",
      secondary: "#B91C1C",
      secondaryForeground: "#FFFFFF",
      accent: "#FACC15",
      accentForeground: "#2A1700",
      border: "#F5E2D3",
      muted: "#FBF0E6",
      mutedForeground: "#8A6F60",
      ring: "#F97316",
      gradientFrom: "#C2410C",
      gradientTo: "#FACC15",
    },
    dark: {
      background: "#1A0F0A",
      foreground: "#FDF2EA",
      card: "#2A1810",
      cardForeground: "#FDF2EA",
      primary: "#FB923C",
      primaryForeground: "#1A0F0A",
      secondary: "#F87171",
      secondaryForeground: "#1A0F0A",
      accent: "#FDE047",
      accentForeground: "#2A1700",
      border: "#3D2418",
      muted: "#2F1B12",
      mutedForeground: "#C2A28F",
      ring: "#FB923C",
      gradientFrom: "#F97316",
      gradientTo: "#FDE047",
    },
  },
  {
    id: "rosegold",
    name: "Rose Gold",
    description: "Elegant",
    swatch: "#E8849C",
    light: {
      background: "#FFF8F9",
      foreground: "#2A1820",
      card: "#FFFFFF",
      cardForeground: "#2A1820",
      primary: "#BE185D",
      primaryForeground: "#FFFFFF",
      secondary: "#9D174D",
      secondaryForeground: "#FFFFFF",
      accent: "#E8C468",
      accentForeground: "#2A1F03",
      border: "#F6E0E6",
      muted: "#FBEEF1",
      mutedForeground: "#8A6B73",
      ring: "#E8849C",
      gradientFrom: "#BE185D",
      gradientTo: "#E8C468",
    },
    dark: {
      background: "#1A0F14",
      foreground: "#FBEEF1",
      card: "#2A1822",
      cardForeground: "#FBEEF1",
      primary: "#F472B6",
      primaryForeground: "#1A0F14",
      secondary: "#FB7185",
      secondaryForeground: "#1A0F14",
      accent: "#F0CE7A",
      accentForeground: "#2A1F03",
      border: "#3D2530",
      muted: "#2F1B25",
      mutedForeground: "#C2A0AB",
      ring: "#F472B6",
      gradientFrom: "#F472B6",
      gradientTo: "#F0CE7A",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Corporate",
    swatch: "#475569",
    light: {
      background: "#F8FAFC",
      foreground: "#0F172A",
      card: "#FFFFFF",
      cardForeground: "#0F172A",
      primary: "#1E293B",
      primaryForeground: "#FFFFFF",
      secondary: "#334155",
      secondaryForeground: "#FFFFFF",
      accent: "#3B82F6",
      accentForeground: "#FFFFFF",
      border: "#E2E8F0",
      muted: "#F1F5F9",
      mutedForeground: "#64748B",
      ring: "#475569",
      gradientFrom: "#1E293B",
      gradientTo: "#3B82F6",
    },
    dark: {
      background: "#070A12",
      foreground: "#F1F5F9",
      card: "#121826",
      cardForeground: "#F1F5F9",
      primary: "#94A3B8",
      primaryForeground: "#070A12",
      secondary: "#64748B",
      secondaryForeground: "#F1F5F9",
      accent: "#60A5FA",
      accentForeground: "#070A12",
      border: "#1E2738",
      muted: "#161D2C",
      mutedForeground: "#94A1B8",
      ring: "#60A5FA",
      gradientFrom: "#334155",
      gradientTo: "#60A5FA",
    },
  },
  {
    id: "slate",
    name: "Slate",
    description: "Minimal",
    swatch: "#737373",
    light: {
      background: "#FAFAFA",
      foreground: "#1C1C1C",
      card: "#FFFFFF",
      cardForeground: "#1C1C1C",
      primary: "#404040",
      primaryForeground: "#FFFFFF",
      secondary: "#737373",
      secondaryForeground: "#FFFFFF",
      accent: "#D97706",
      accentForeground: "#FFFFFF",
      border: "#E5E5E5",
      muted: "#F5F5F5",
      mutedForeground: "#737373",
      ring: "#737373",
      gradientFrom: "#404040",
      gradientTo: "#D97706",
    },
    dark: {
      background: "#0A0A0A",
      foreground: "#F5F5F5",
      card: "#171717",
      cardForeground: "#F5F5F5",
      primary: "#D4D4D4",
      primaryForeground: "#0A0A0A",
      secondary: "#A3A3A3",
      secondaryForeground: "#0A0A0A",
      accent: "#FBBF24",
      accentForeground: "#0A0A0A",
      border: "#262626",
      muted: "#1A1A1A",
      mutedForeground: "#A3A3A3",
      ring: "#D4D4D4",
      gradientFrom: "#525252",
      gradientTo: "#FBBF24",
    },
  },
  {
    id: "sapphire",
    name: "Sapphire",
    description: "Professional",
    swatch: "#2563EB",
    light: {
      background: "#F7F9FF",
      foreground: "#101828",
      card: "#FFFFFF",
      cardForeground: "#101828",
      primary: "#1D4ED8",
      primaryForeground: "#FFFFFF",
      secondary: "#4338CA",
      secondaryForeground: "#FFFFFF",
      accent: "#06B6D4",
      accentForeground: "#FFFFFF",
      border: "#E0E7FF",
      muted: "#EEF2FF",
      mutedForeground: "#5C6587",
      ring: "#2563EB",
      gradientFrom: "#1D4ED8",
      gradientTo: "#06B6D4",
    },
    dark: {
      background: "#070B1A",
      foreground: "#E8ECFB",
      card: "#101632",
      cardForeground: "#E8ECFB",
      primary: "#60A5FA",
      primaryForeground: "#070B1A",
      secondary: "#818CF8",
      secondaryForeground: "#070B1A",
      accent: "#22D3EE",
      accentForeground: "#070B1A",
      border: "#1E2A4D",
      muted: "#141B38",
      mutedForeground: "#8E9BC4",
      ring: "#60A5FA",
      gradientFrom: "#3B82F6",
      gradientTo: "#22D3EE",
    },
  },
];

export const DEFAULT_THEME_ID = "royal";

export function getPreset(id: string): ThemePreset {
  return THEME_PRESETS.find((p) => p.id === id) || THEME_PRESETS[0];
}
